AllCops:
  TargetRubyVersion: 2.5
  DisplayStyleGuide: true
  Include:
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'app/controllers/users/*'
    - 'test/test_helper.rb'
    - 'app/controllers/statistics_controller.rb'


Rails:
  Enabled: true

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  IgnoredPatterns: ['\A\s*#']
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 10
  
Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/InverseOf:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false


